# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Enable Docker for Testcontainers
      run: |
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV

    - name: Restore Aspire workload
      run: dotnet workload install aspire    
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
        TESTCONTAINERS_RYUK_DISABLED: "true"
      run: dotnet test
